spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:poker_joker}
    username: ${PGUSER:poker}
    password: ${PGPASSWORD:poker}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}